/* Generated by Yosys 0.56 (git sha1 9c447ad9d4b1ea589369364eea38b4d70da2c599, clang++ 17.0.0 -fPIC -O3) */

module async_fifo_4x4(wr_clk, rd_clk, rst_n, wr_en, rd_en, din, dout, full, empty);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  input [3:0] din;
  wire [3:0] din;
  output [3:0] dout;
  wire [3:0] dout;
  output empty;
  wire empty;
  wire empty_nxt;
  wire empty_r;
  output full;
  wire full;
  wire full_nxt;
  wire full_r;
  wire [3:0] \mem[0] ;
  wire [3:0] \mem[1] ;
  wire [3:0] \mem[2] ;
  wire [3:0] \mem[3] ;
  input rd_clk;
  wire rd_clk;
  input rd_en;
  wire rd_en;
  wire [2:0] rptr_bin;
  wire [2:0] rptr_bin_nxt;
  wire [2:0] rptr_gray;
  wire [2:0] rptr_gray_nxt;
  wire [2:0] rptr_gray_sync_w1;
  wire [2:0] rptr_gray_sync_w2;
  wire [2:0] rptr_gray_wr;
  input rst_n;
  wire rst_n;
  wire [2:0] wptr_bin;
  wire [2:0] wptr_bin_nxt;
  wire [2:0] wptr_gray;
  wire [2:0] wptr_gray_nxt;
  wire [2:0] wptr_gray_rd;
  wire [2:0] wptr_gray_sync_r1;
  wire [2:0] wptr_gray_sync_r2;
  input wr_clk;
  wire wr_clk;
  input wr_en;
  wire wr_en;
  INV_X1 _107_ (
    .A(wr_en),
    .ZN(_047_)
  );
  INV_X1 _108_ (
    .A(wptr_bin[1]),
    .ZN(_048_)
  );
  INV_X1 _109_ (
    .A(rd_en),
    .ZN(_049_)
  );
  INV_X1 _110_ (
    .A(rptr_bin[1]),
    .ZN(_050_)
  );
  INV_X1 _111_ (
    .A(rptr_bin[0]),
    .ZN(_051_)
  );
  NOR2_X1 _112_ (
    .A1(full_r),
    .A2(_047_),
    .ZN(_052_)
  );
  XOR2_X1 _113_ (
    .A(wptr_bin[0]),
    .B(_052_),
    .Z(wptr_bin_nxt[0])
  );
  NOR3_X1 _114_ (
    .A1(full_r),
    .A2(_047_),
    .A3(_000_),
    .ZN(_053_)
  );
  AND2_X1 _115_ (
    .A1(wptr_bin[1]),
    .A2(_053_),
    .ZN(_054_)
  );
  NOR2_X1 _116_ (
    .A1(wptr_bin[1]),
    .A2(_053_),
    .ZN(_055_)
  );
  XNOR2_X1 _117_ (
    .A(wptr_bin[1]),
    .B(_053_),
    .ZN(_056_)
  );
  INV_X1 _118_ (
    .A(_056_),
    .ZN(wptr_bin_nxt[1])
  );
  XNOR2_X1 _119_ (
    .A(wptr_bin_nxt[0]),
    .B(_056_),
    .ZN(wptr_gray_nxt[0])
  );
  XNOR2_X1 _120_ (
    .A(wptr_bin[2]),
    .B(_055_),
    .ZN(wptr_gray_nxt[1])
  );
  XOR2_X1 _121_ (
    .A(rptr_gray_sync_w2[0]),
    .B(wptr_gray_nxt[0]),
    .Z(_057_)
  );
  XNOR2_X1 _122_ (
    .A(rptr_gray_sync_w2[1]),
    .B(wptr_gray_nxt[1]),
    .ZN(_058_)
  );
  XOR2_X1 _123_ (
    .A(wptr_bin[2]),
    .B(_054_),
    .Z(wptr_bin_nxt[2])
  );
  XNOR2_X1 _124_ (
    .A(rptr_gray_sync_w2[2]),
    .B(wptr_bin_nxt[2]),
    .ZN(_059_)
  );
  NOR3_X1 _125_ (
    .A1(_057_),
    .A2(_058_),
    .A3(_059_),
    .ZN(full_nxt)
  );
  NOR2_X1 _126_ (
    .A1(empty_r),
    .A2(_049_),
    .ZN(_060_)
  );
  NOR3_X1 _127_ (
    .A1(empty_r),
    .A2(_049_),
    .A3(_001_),
    .ZN(_061_)
  );
  AND2_X1 _128_ (
    .A1(rptr_bin[1]),
    .A2(_061_),
    .ZN(_062_)
  );
  NOR2_X1 _129_ (
    .A1(rptr_bin[1]),
    .A2(_061_),
    .ZN(_063_)
  );
  XNOR2_X1 _130_ (
    .A(rptr_bin[1]),
    .B(_061_),
    .ZN(_064_)
  );
  INV_X1 _131_ (
    .A(_064_),
    .ZN(rptr_bin_nxt[1])
  );
  XNOR2_X1 _132_ (
    .A(_051_),
    .B(_060_),
    .ZN(rptr_bin_nxt[0])
  );
  XNOR2_X1 _133_ (
    .A(_064_),
    .B(rptr_bin_nxt[0]),
    .ZN(rptr_gray_nxt[0])
  );
  XNOR2_X1 _134_ (
    .A(rptr_bin[2]),
    .B(_063_),
    .ZN(rptr_gray_nxt[1])
  );
  XNOR2_X1 _135_ (
    .A(wptr_gray_sync_r2[0]),
    .B(rptr_gray_nxt[0]),
    .ZN(_022_)
  );
  XOR2_X1 _136_ (
    .A(rptr_bin[2]),
    .B(_062_),
    .Z(rptr_bin_nxt[2])
  );
  XNOR2_X1 _137_ (
    .A(wptr_gray_sync_r2[2]),
    .B(rptr_bin_nxt[2]),
    .ZN(_023_)
  );
  XNOR2_X1 _138_ (
    .A(wptr_gray_sync_r2[1]),
    .B(rptr_gray_nxt[1]),
    .ZN(_024_)
  );
  AND3_X1 _139_ (
    .A1(_022_),
    .A2(_023_),
    .A3(_024_),
    .ZN(empty_nxt)
  );
  NAND4_X1 _140_ (
    .A1(rst_n),
    .A2(wptr_bin[0]),
    .A3(wptr_bin[1]),
    .A4(_052_),
    .ZN(_025_)
  );
  MUX2_X1 _141_ (
    .A(din[0]),
    .B(\mem[3] [0]),
    .S(_025_),
    .Z(_002_)
  );
  MUX2_X1 _142_ (
    .A(din[1]),
    .B(\mem[3] [1]),
    .S(_025_),
    .Z(_003_)
  );
  MUX2_X1 _143_ (
    .A(din[2]),
    .B(\mem[3] [2]),
    .S(_025_),
    .Z(_004_)
  );
  MUX2_X1 _144_ (
    .A(din[3]),
    .B(\mem[3] [3]),
    .S(_025_),
    .Z(_005_)
  );
  NAND3_X1 _145_ (
    .A1(rst_n),
    .A2(_048_),
    .A3(_052_),
    .ZN(_026_)
  );
  NOR2_X1 _146_ (
    .A1(wptr_bin[0]),
    .A2(_026_),
    .ZN(_027_)
  );
  MUX2_X1 _147_ (
    .A(\mem[0] [0]),
    .B(din[0]),
    .S(_027_),
    .Z(_010_)
  );
  MUX2_X1 _148_ (
    .A(\mem[0] [1]),
    .B(din[1]),
    .S(_027_),
    .Z(_011_)
  );
  MUX2_X1 _149_ (
    .A(\mem[0] [2]),
    .B(din[2]),
    .S(_027_),
    .Z(_012_)
  );
  MUX2_X1 _150_ (
    .A(\mem[0] [3]),
    .B(din[3]),
    .S(_027_),
    .Z(_013_)
  );
  NAND4_X1 _151_ (
    .A1(rst_n),
    .A2(wptr_bin[0]),
    .A3(_048_),
    .A4(_052_),
    .ZN(_028_)
  );
  MUX2_X1 _152_ (
    .A(din[0]),
    .B(\mem[1] [0]),
    .S(_028_),
    .Z(_014_)
  );
  MUX2_X1 _153_ (
    .A(din[1]),
    .B(\mem[1] [1]),
    .S(_028_),
    .Z(_015_)
  );
  MUX2_X1 _154_ (
    .A(din[2]),
    .B(\mem[1] [2]),
    .S(_028_),
    .Z(_016_)
  );
  MUX2_X1 _155_ (
    .A(din[3]),
    .B(\mem[1] [3]),
    .S(_028_),
    .Z(_017_)
  );
  NAND3_X1 _156_ (
    .A1(rst_n),
    .A2(wptr_bin[1]),
    .A3(_052_),
    .ZN(_029_)
  );
  NOR2_X1 _157_ (
    .A1(wptr_bin[0]),
    .A2(_029_),
    .ZN(_030_)
  );
  MUX2_X1 _158_ (
    .A(\mem[2] [0]),
    .B(din[0]),
    .S(_030_),
    .Z(_018_)
  );
  MUX2_X1 _159_ (
    .A(\mem[2] [1]),
    .B(din[1]),
    .S(_030_),
    .Z(_019_)
  );
  MUX2_X1 _160_ (
    .A(\mem[2] [2]),
    .B(din[2]),
    .S(_030_),
    .Z(_020_)
  );
  MUX2_X1 _161_ (
    .A(\mem[2] [3]),
    .B(din[3]),
    .S(_030_),
    .Z(_021_)
  );
  NOR2_X1 _162_ (
    .A1(_050_),
    .A2(rptr_bin[0]),
    .ZN(_031_)
  );
  NOR2_X1 _163_ (
    .A1(rptr_bin[1]),
    .A2(_051_),
    .ZN(_032_)
  );
  AOI22_X1 _164_ (
    .A1(\mem[2] [0]),
    .A2(_031_),
    .B1(_032_),
    .B2(\mem[1] [0]),
    .ZN(_033_)
  );
  NOR2_X1 _165_ (
    .A1(_050_),
    .A2(_051_),
    .ZN(_034_)
  );
  NOR2_X1 _166_ (
    .A1(rptr_bin[1]),
    .A2(rptr_bin[0]),
    .ZN(_035_)
  );
  AOI22_X1 _167_ (
    .A1(\mem[3] [0]),
    .A2(_034_),
    .B1(_035_),
    .B2(\mem[0] [0]),
    .ZN(_036_)
  );
  NAND2_X1 _168_ (
    .A1(_033_),
    .A2(_036_),
    .ZN(_037_)
  );
  MUX2_X1 _169_ (
    .A(dout[0]),
    .B(_037_),
    .S(_060_),
    .Z(_006_)
  );
  AOI22_X1 _170_ (
    .A1(\mem[3] [1]),
    .A2(_034_),
    .B1(_035_),
    .B2(\mem[0] [1]),
    .ZN(_038_)
  );
  AOI22_X1 _171_ (
    .A1(\mem[2] [1]),
    .A2(_031_),
    .B1(_032_),
    .B2(\mem[1] [1]),
    .ZN(_039_)
  );
  NAND2_X1 _172_ (
    .A1(_038_),
    .A2(_039_),
    .ZN(_040_)
  );
  MUX2_X1 _173_ (
    .A(dout[1]),
    .B(_040_),
    .S(_060_),
    .Z(_007_)
  );
  AOI22_X1 _174_ (
    .A1(\mem[3] [2]),
    .A2(_034_),
    .B1(_035_),
    .B2(\mem[0] [2]),
    .ZN(_041_)
  );
  AOI22_X1 _175_ (
    .A1(\mem[2] [2]),
    .A2(_031_),
    .B1(_032_),
    .B2(\mem[1] [2]),
    .ZN(_042_)
  );
  NAND2_X1 _176_ (
    .A1(_041_),
    .A2(_042_),
    .ZN(_043_)
  );
  MUX2_X1 _177_ (
    .A(dout[2]),
    .B(_043_),
    .S(_060_),
    .Z(_008_)
  );
  AOI22_X1 _178_ (
    .A1(\mem[2] [3]),
    .A2(_031_),
    .B1(_032_),
    .B2(\mem[1] [3]),
    .ZN(_044_)
  );
  AOI22_X1 _179_ (
    .A1(\mem[3] [3]),
    .A2(_034_),
    .B1(_035_),
    .B2(\mem[0] [3]),
    .ZN(_045_)
  );
  NAND2_X1 _180_ (
    .A1(_044_),
    .A2(_045_),
    .ZN(_046_)
  );
  MUX2_X1 _181_ (
    .A(dout[3]),
    .B(_046_),
    .S(_060_),
    .Z(_009_)
  );
  DFF_X1 _182_ (
    .CK(wr_clk),
    .D(_002_),
    .Q(\mem[3] [0]),
    .QN(_084_)
  );
  DFF_X1 _183_ (
    .CK(wr_clk),
    .D(_003_),
    .Q(\mem[3] [1]),
    .QN(_083_)
  );
  DFF_X1 _184_ (
    .CK(wr_clk),
    .D(_004_),
    .Q(\mem[3] [2]),
    .QN(_082_)
  );
  DFF_X1 _185_ (
    .CK(wr_clk),
    .D(_005_),
    .Q(\mem[3] [3]),
    .QN(_085_)
  );
  DFFR_X1 _186_ (
    .CK(rd_clk),
    .D(wptr_gray[0]),
    .Q(wptr_gray_sync_r1[0]),
    .QN(_086_),
    .RN(rst_n)
  );
  DFFR_X1 _187_ (
    .CK(rd_clk),
    .D(wptr_gray[1]),
    .Q(wptr_gray_sync_r1[1]),
    .QN(_087_),
    .RN(rst_n)
  );
  DFFR_X1 _188_ (
    .CK(rd_clk),
    .D(wptr_bin[2]),
    .Q(wptr_gray_sync_r1[2]),
    .QN(_088_),
    .RN(rst_n)
  );
  DFFR_X1 _189_ (
    .CK(rd_clk),
    .D(wptr_gray_sync_r1[0]),
    .Q(wptr_gray_sync_r2[0]),
    .QN(_089_),
    .RN(rst_n)
  );
  DFFR_X1 _190_ (
    .CK(rd_clk),
    .D(wptr_gray_sync_r1[1]),
    .Q(wptr_gray_sync_r2[1]),
    .QN(_090_),
    .RN(rst_n)
  );
  DFFR_X1 _191_ (
    .CK(rd_clk),
    .D(wptr_gray_sync_r1[2]),
    .Q(wptr_gray_sync_r2[2]),
    .QN(_091_),
    .RN(rst_n)
  );
  DFFR_X1 _192_ (
    .CK(rd_clk),
    .D(rptr_bin_nxt[0]),
    .Q(rptr_bin[0]),
    .QN(_001_),
    .RN(rst_n)
  );
  DFFR_X1 _193_ (
    .CK(rd_clk),
    .D(rptr_bin_nxt[1]),
    .Q(rptr_bin[1]),
    .QN(_092_),
    .RN(rst_n)
  );
  DFFR_X1 _194_ (
    .CK(rd_clk),
    .D(rptr_bin_nxt[2]),
    .Q(rptr_bin[2]),
    .QN(_093_),
    .RN(rst_n)
  );
  DFFR_X1 _195_ (
    .CK(rd_clk),
    .D(rptr_gray_nxt[0]),
    .Q(rptr_gray[0]),
    .QN(_094_),
    .RN(rst_n)
  );
  DFFR_X1 _196_ (
    .CK(rd_clk),
    .D(rptr_gray_nxt[1]),
    .Q(rptr_gray[1]),
    .QN(_095_),
    .RN(rst_n)
  );
  DFFS_X1 _197_ (
    .CK(rd_clk),
    .D(empty_nxt),
    .Q(empty_r),
    .QN(_096_),
    .SN(rst_n)
  );
  DFFR_X1 _198_ (
    .CK(wr_clk),
    .D(rptr_gray[0]),
    .Q(rptr_gray_sync_w1[0]),
    .QN(_097_),
    .RN(rst_n)
  );
  DFFR_X1 _199_ (
    .CK(wr_clk),
    .D(rptr_gray[1]),
    .Q(rptr_gray_sync_w1[1]),
    .QN(_098_),
    .RN(rst_n)
  );
  DFFR_X1 _200_ (
    .CK(wr_clk),
    .D(rptr_bin[2]),
    .Q(rptr_gray_sync_w1[2]),
    .QN(_099_),
    .RN(rst_n)
  );
  DFFR_X1 _201_ (
    .CK(wr_clk),
    .D(rptr_gray_sync_w1[0]),
    .Q(rptr_gray_sync_w2[0]),
    .QN(_100_),
    .RN(rst_n)
  );
  DFFR_X1 _202_ (
    .CK(wr_clk),
    .D(rptr_gray_sync_w1[1]),
    .Q(rptr_gray_sync_w2[1]),
    .QN(_101_),
    .RN(rst_n)
  );
  DFFR_X1 _203_ (
    .CK(wr_clk),
    .D(rptr_gray_sync_w1[2]),
    .Q(rptr_gray_sync_w2[2]),
    .QN(_102_),
    .RN(rst_n)
  );
  DFFR_X1 _204_ (
    .CK(wr_clk),
    .D(wptr_bin_nxt[0]),
    .Q(wptr_bin[0]),
    .QN(_000_),
    .RN(rst_n)
  );
  DFFR_X1 _205_ (
    .CK(wr_clk),
    .D(wptr_bin_nxt[1]),
    .Q(wptr_bin[1]),
    .QN(_103_),
    .RN(rst_n)
  );
  DFFR_X1 _206_ (
    .CK(wr_clk),
    .D(wptr_bin_nxt[2]),
    .Q(wptr_bin[2]),
    .QN(_104_),
    .RN(rst_n)
  );
  DFFR_X1 _207_ (
    .CK(wr_clk),
    .D(wptr_gray_nxt[0]),
    .Q(wptr_gray[0]),
    .QN(_105_),
    .RN(rst_n)
  );
  DFFR_X1 _208_ (
    .CK(wr_clk),
    .D(wptr_gray_nxt[1]),
    .Q(wptr_gray[1]),
    .QN(_106_),
    .RN(rst_n)
  );
  DFFR_X1 _209_ (
    .CK(wr_clk),
    .D(full_nxt),
    .Q(full_r),
    .QN(_081_),
    .RN(rst_n)
  );
  DFFR_X1 _210_ (
    .CK(rd_clk),
    .D(_006_),
    .Q(dout[0]),
    .QN(_080_),
    .RN(rst_n)
  );
  DFFR_X1 _211_ (
    .CK(rd_clk),
    .D(_007_),
    .Q(dout[1]),
    .QN(_079_),
    .RN(rst_n)
  );
  DFFR_X1 _212_ (
    .CK(rd_clk),
    .D(_008_),
    .Q(dout[2]),
    .QN(_078_),
    .RN(rst_n)
  );
  DFFR_X1 _213_ (
    .CK(rd_clk),
    .D(_009_),
    .Q(dout[3]),
    .QN(_077_),
    .RN(rst_n)
  );
  DFF_X1 _214_ (
    .CK(wr_clk),
    .D(_010_),
    .Q(\mem[0] [0]),
    .QN(_076_)
  );
  DFF_X1 _215_ (
    .CK(wr_clk),
    .D(_011_),
    .Q(\mem[0] [1]),
    .QN(_075_)
  );
  DFF_X1 _216_ (
    .CK(wr_clk),
    .D(_012_),
    .Q(\mem[0] [2]),
    .QN(_074_)
  );
  DFF_X1 _217_ (
    .CK(wr_clk),
    .D(_013_),
    .Q(\mem[0] [3]),
    .QN(_073_)
  );
  DFF_X1 _218_ (
    .CK(wr_clk),
    .D(_014_),
    .Q(\mem[1] [0]),
    .QN(_072_)
  );
  DFF_X1 _219_ (
    .CK(wr_clk),
    .D(_015_),
    .Q(\mem[1] [1]),
    .QN(_071_)
  );
  DFF_X1 _220_ (
    .CK(wr_clk),
    .D(_016_),
    .Q(\mem[1] [2]),
    .QN(_070_)
  );
  DFF_X1 _221_ (
    .CK(wr_clk),
    .D(_017_),
    .Q(\mem[1] [3]),
    .QN(_069_)
  );
  DFF_X1 _222_ (
    .CK(wr_clk),
    .D(_018_),
    .Q(\mem[2] [0]),
    .QN(_068_)
  );
  DFF_X1 _223_ (
    .CK(wr_clk),
    .D(_019_),
    .Q(\mem[2] [1]),
    .QN(_067_)
  );
  DFF_X1 _224_ (
    .CK(wr_clk),
    .D(_020_),
    .Q(\mem[2] [2]),
    .QN(_066_)
  );
  DFF_X1 _225_ (
    .CK(wr_clk),
    .D(_021_),
    .Q(\mem[2] [3]),
    .QN(_065_)
  );
  assign empty = empty_r;
  assign full = full_r;
  assign rptr_gray[2] = rptr_bin[2];
  assign rptr_gray_nxt[2] = rptr_bin_nxt[2];
  assign rptr_gray_wr = rptr_gray_sync_w2;
  assign wptr_gray[2] = wptr_bin[2];
  assign wptr_gray_nxt[2] = wptr_bin_nxt[2];
  assign wptr_gray_rd = wptr_gray_sync_r2;
endmodule
